DROP TABLE IF EXISTS `produto`;
CREATE TABLE `produto` (
  `id` int(11)  NOT NULL,
  `linxbi_uni` int(11)  DEFAULT NULL,
  `loj_codigo` tinyint(1)  DEFAULT NULL,
  `pro_codigo` int(11)  DEFAULT NULL,
  `grp_codigo` int(11)  DEFAULT NULL,
  `pro_descricao` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_unidade` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_ativo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_dtdesativacao` datetime DEFAULT NULL,
  `pro_codigoprincipal` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_descresumida` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_acompanhamento` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_participatc` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `ocs_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cso_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pis_cst` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cof_cst` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cmi_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cms_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_redbc` decimal(10,2) DEFAULT NULL,
  `pro_redbcst` decimal(10,2) DEFAULT NULL,
  `pro_estoque` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_obsobrigatoria` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imagem` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imagemmobile` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imagemmobile_versao` tinyint(1)  DEFAULT NULL,
  `pro_imagemautoatend` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imagemautoatend_versao` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imagemvenda` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imagemvenda_versao` int(11)  DEFAULT NULL,
  `pro_descricaodetalhada` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_mixproduto` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_considvlrprodprincipal` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_compautomaticamente` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_priorizar` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `leg_codigoprodprinc` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_dataimportacao` datetime DEFAULT NULL,
  `pro_codigointegracao` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_codigoreferencia` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `mdi_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_callsincronizado` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_restricaohorario` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_cest` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_imprdeptodesmembrarvo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_codigointegracao3` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_registrar` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_restricaodia` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_domingo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_segunda` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_terca` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_quarta` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_quinta` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_sexta` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_sabado` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `lip_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `cla_codigo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_combardentrovo` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_trabvalorrefe` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `rep_datahora` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_tempoproducao` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_aliqfcp` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_relevante` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_relevantecnpj` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_corfontetrp` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `pro_corfundotrp` varchar(191) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) 