User:
  fields:
    name:
      schema: string
      rules: required
      tags: fillable
    email:
      schema: string
      rules: required
      tags: fillable 
    password:
      schema: string
      rules: required
      tags: fillable 
    profile_img:
      schema: string nullable
      tags: fillable
    raw_login_info:
      schema: text nullable
      tags: fillable
    access_token:
      schema: text nullable
      tags: fillable   
  add: timestamps softDeletes
Payment:
  fields:
    name:
      schema: string
      rules: required
      tags: fillable
    total:
      schema: double nullable
      tags: fillable
    dados:
      schema: text nullable
      tags: fillable
    shop:
      schema: integer
      rules: required
      tags: fillable
    type:
      schema: integer
      rules: required
      tags: fillable  
    user:
      schema: integer
      rules: required
      tags: fillable
    nfe:
      schema: text nullable
      tags: fillable
    tid:
      schema: string nullable
      tags: fillable    
  add: timestamps  
