User:
  belongsTo: group
  fields:
    name:
      schema: string
      rules: required
      tags: fillable
    email:
      schema: string
      rules: required
      tags: fillable
    user_token:
      schema: string
      rules: required
      tags: fillable  
    password:
      schema: text nullable
      tags: fillable
    logado:
      schema: integer
      rules: required
      tags: fillable
    login:
      schema: text nullable
      tags: fillable
    imagem:
      schema: text nullable
      tags: fillable     
    wallet:
      schema: double
      rules: required
      tags: fillable  
    profile_img:
      schema: string nullable
      tags: fillable
    raw_login_info:
      schema: text nullable
      tags: fillable
    subscription_id:
      schema: text nullable
      tags: fillable  
    parent_user:
      schema: integer nullable
      tags: fillable  
    access_token:
      schema: text nullable
      tags: fillable   
  add: timestamps softDeletes
Group:
  hasMany: users
  fields:
    name:
      schema: string
      rules: required
      tags: fillable
    desc:
      schema: text nullable
      tags: fillable
  add: timestamps
Shop:
  fields:
    name:
      schema: string
      rules: required
      tags: fillable
    total:
      schema: double nullable
      tags: fillable
  add: timestamps   
Payment:
  fields:
    name:
      schema: string
      rules: required
      tags: fillable
    total:
      schema: double nullable
      tags: fillable
    dados:
      schema: text nullable
      tags: fillable
    shop:
      schema: integer
      rules: required
      tags: fillable
    type:
      schema: integer
      rules: required
      tags: fillable  
    user:
      schema: integer
      rules: required
      tags: fillable
    nfe:
      schema: text nullable
      tags: fillable
    tid:
      schema: string nullable
      tags: fillable    
  add: timestamps
BenAmigo:
  fields:
    eu:
      schema: text
      rules: required
      tags: fillable
    amigo:
      schema: text
      rules: required
      tags: fillable
    relationship:
      schema: integer nullable
      tags: fillable
    status:
      schema: integer nullable
      tags: fillable  
  add: timestamps     
