<div class="page-header header-filter header-small" data-parallax="true" style="background-image: url(&quot;/assets/img/benja.jpg&quot;); transform: translate3d(0px, 0px, 0px);">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto text-center">
          <h1 class="title">Termos de uso e privacidade</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container"><br>
      <div class="about-description">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <h4>Obrigado por usar o aplicativo da IB Café denominado neste documento e em suas tecnologias como Benjamin A Padaria A Padaria. Ao seguir,(doravante denominado "aplicativo Benjamin A Padaria"), o usuário concorda com os seguintes termos e condições (doravante denominados "Termos e Condições da Benjamin A Padaria"). O aplicativo Benjamin A Padaria e qualquer componente deste produto são mencionados neste documento como o "Software".
            </h4>
          </div>
        </div>
      </div>
      <div class="about-team team-1">
        <div class="row">
          <div class="col-md-12 ml-auto mr-auto">
            <h4 class="info-title">1. USO DO SOFTWARE</h4>
            <h4>Nestes Termos e Condições, a Benjamin A Padaria  concede ao usuário uma licença não-exclusiva e intransferível de uso do Software distribuído junto com este Contrato, durante a vigência do prazo do Contrato, para uso em uma única conta designado. A mencionada licença será de uso único, a critério exclusivo da Benjamin A Padaria , e é condicionada ao recebimento, pela Benjamin A Padaria . 
            Os direitos do usuário no que se refere ao Software são limitados àqueles explicitamente concedidos nesta Seção 1. Os direitos do usuário no que se refere ao Software não abarcam nenhum tipo de transmissão ou uso de mídia, exceto por contrato separado para obtenção de permissão da Benjamin A Padaria  para tanto. As informações disponibilizadas para exibição mediante o uso do Software são fornecidas na forma de uma licença não-exclusiva e intransferível, para fins de impressão e para uso apenas do usuário. Todas as animações, filmes, impressões ou saídas de tela gerados pelo Software são para uso exclusivo da Benjamin A Padaria . Não é permitido usar o Software de qualquer maneira que possa danificar, desativar, sobrecarregar ou prejudicar os serviços da Benjamin A Padaria  (por exemplo, é proibido usar o Software de forma automatizada) ou de qualquer modo que possa interferir no uso e aproveitamento dos serviços da Benjamin A Padaria  por parte de terceiros.</h4>
            <h4 class="info-title">2. POLÍTICA DE PRIVACIDADE</h4>
            <h4>A proteção da privacidade dos usuários é muito importante para a Benjamin A Padaria . Como condição para usar o Software, o usuário concorda com os termos da Política de Privacidade do aplicativo da Benjamin A Padaria . Que poderá ser atualizada periodicamente e sem aviso prévio. As informações coletadas pela Benjamin  em relação ao uso do Software poderão ser armazenadas e processadas no Brasil,ou em qualquer outro país onde a Benjamin A Padaria ou seus agentes mantenham instalações porém sempre avisando por meio da sua plataforma diretamente ao usuário. Assim sendo, ao usar o Software, o usuário consente que tais informações sejam transferidas para fora de seu país. O usuário reconhece e concorda que a Benjamin A Padaria  acesse, preserve e divulgue as informações de sua conta quando assim exigido por autoridades jurídicas ou quando acreditar de boa-fé de que o referido acesso, preservação ou divulgação seja necessário para: (a) satisfazer qualquer legislação, regulamentação, processo jurídico ou solicitação governamental aplicável; (b) impor estes Termos e Condições, incluindo a investigação de suas possíveis violações; (c) detectar, impedir ou abordar problemas técnicos, de fraude e de segurança (incluindo, sem limitação, filtragem de spams); (d) atender a solicitações de suporte do usuário ou (e) proteger os direitos, a propriedade ou a segurança da Benjamin A Padaria , de seus usuários e do público. A Benjamin A Padaria  não será responsável pelo cumprimento ou não dos direitos previstos nestes Termos e Condições.6</h4>
            <h4 class="info-title">3. DIREITOS RESERVADOS</h4>
            <h4>O usuário reconhece que  o Software da Benjamin a Padaria contém informações reservadas e confidenciais protegidas por leis de propriedade intelectual  criptografadas em seu nível mais sensivel, reservada somente a somente um funcionário da mesma somente via solicitação judicial podendo ser cedida. aplicáveis e outras leis, e (b) a Benjamin A Padaria  é proprietário de todos os direitos, títulos e participações referentes ao Software e a qualquer outro aplicativo fornecido junto com o Software, incluindo, sem limitação, todos os Direitos de Propriedade Intelectual vinculados ao Software. "Direitos de Propriedade Intelectual" significa todo e qualquer direito existente periodicamente sob as leis de patente, de direito autoral, de segredo comercial, de marca comercial, de concorrência desleal e todos os outros direitos proprietários, bem como sob todos os aplicativos, renovações, extensões e restaurações decorrentes, agora ou doravante vigentes no mundo inteiro. O usuário concorda que não fará nem permitirá a terceiros fazer o seguinte: (i) tomar qualquer providência para burlar ou anular as regras de segurança ou utilização de conteúdo fornecidas, implementadas ou impostas por qualquer funcionalidade (incluindo, sem limitação, a funcionalidade de gerenciamento de direitos digitais) oferecida no Software; (ii) usar o Software para acessar, copiar, transferir, transcodificar ou re transmitir conteúdo violando qualquer lei ou os direitos de terceiros; ou (iii) remover, ocultar ou alterar avisos de direito autoral, de marca registrada ou outros avisos de direitos proprietários da Benjamin A Padaria  afixados ou contidos no Software ou acessados em conjunto com o Software.</h4>
            <h4 class="info-title">4. DIREITOS RESTRITOS DO GOVERNO DO BRASIL</h4>
            <h4>O Software e qualquer documentação relacionada são considerados "software comercial" e "documentação de software comercial", respectivamente, dentro do contexto das regulamentações de aquisições Federais Civis e Militares aplicáveis e de qualquer suplemento referente a elas. Se o usuário do Software for um órgão, departamento, funcionário ou outra entidade do Governo Brasileiro, o uso, duplicação, reprodução, liberação, modificação, divulgação ou transferência do Software, incluindo os manuais ou dados técnicos, estará restrito pelos termos, condições e compromissos contidos nestes Termos e Condições da Benjamin A Padaria . De acordo com a regulamentação de aquisições federais – para órgãos civis e o suplemento à regulamentação de aquisições federais de defesa – o uso do Software também é restrito de acordo com estes Termos e Condições da Benjamin A Padaria .</h4>
            <h4 class="info-title">5. CUMPRIMENTO DAS LEIS E POLÍTICAS DA BENJAMIN A PADARIA</h4>
            <h4>Você concorda em cumprir todas as legislações e regulamentações locais referentes a uso do Software. Você concorda em cumprir quaisquer políticas ou orientações aplicáveis que a Benjamin A Padaria divulgue periodicamente a seu exclusivo critério. A título de exemplo, e não como uma limitação, você concorda que, ao usar o Software, não irá:
            <ul> difamar, ofender, importunar, perseguir, ameaçar ou violar os direitos legais (os direitos de privacidade e publicidade, por exemplo) de terceiros;</ul>
            <ul>fazer upload, publicar, enviar por e-mail, transmitir ou divulgar qualquer conteúdo inadequado, difamatório, transgressor, obsceno ou ilegal;
            fazer upload, publicar, enviar por e-mail, transmitir ou divulgar qualquer conteúdo que infrinja qualquer direito de patente, de marca comercial, de direito autoral, de segredo comercial ou outro direito proprietário de terceiros, salvo se o usuário for o proprietário dos respectivos direitos ou tiver permissão do proprietário para publicar o referido conteúdo;</ul>
            <ul>fazer download de qualquer arquivo publicado por outra pessoa que o usuário conheça, ou possa conhecer, que não possa ser distribuído legalmente dessa maneira;
            assumir a identidade de outra pessoa ou entidade, ou falsificar ou excluir quaisquer atribuições do autor, avisos legais ou outros avisos adequados, ou designações ou rótulos proprietários da origem ou fonte do software ou outro material;
            restringir ou inibir qualquer outro usuário no uso e aproveitamento dos serviços da Benjamin A Padaria ;</ul>
            <ul>usar os serviços da Benjamin A Padaria  para qualquer finalidade ilegal ou não autorizada;</ul>
            <ul>remover quaisquer avisos de direito autoral, de marca comercial ou outros direitos proprietários contidos nos serviços da Benjamin A Padaria ;</ul>
            <ul>prejudicar ou interromper os serviços ou servidores da Benjamin A Padaria  ou as redes conectadas aos serviços da Benjamin A Padaria , ou desobedecer a quaisquer exigências, procedimentos, políticas ou regulamentações das redes conectadas aos serviços da Benjamin A Padaria ;</ul>
            <ul>usar qualquer robô, mecanismo de busca, aplicativo de pesquisa/recuperação de sites ou outro dispositivo para recuperar ou indexar qualquer parte dos serviços da Benjamin A Padaria  ou coletar informações sobre os usuários para qualquer finalidade não autorizada;</ul>
            <ul>enviar Conteúdo com propaganda enganosa afirmando que tal conteúdo é patrocinado ou endossado pela Benjamin A Padaria ;</ul>
            <ul>criar contas de usuário por meios automatizados ou com intenções falsas ou fraudulentas;</ul>
            <ul>promover ou fornecer informações sobre atividades ilegais ou promover lesões ou danos físicos a qualquer grupo ou indivíduo;</ul>
            <ul>transmitir qualquer vírus, worms, defeitos, cavalos de Tróia ou quaisquer itens de natureza destrutiva. À risco de perseguição pela equipe de desenvolvimento e aplicabilidade das leis brasileiras. 
            </h4>
            <h4 class="info-title">6. RESCISÃO</h4>
            <h4>O usuário poderá rescindir estes Termos e Condições a qualquer momento deixando de utilizar o Software. Os direitos do usuário serão rescindidos automática e imediatamente sem aviso prévio por parte da Benjamin A Padaria  caso o usuário não esteja em conformidade com alguma cláusula destes Termos e Condições. Nesse caso, o usuário deverá parar o uso imediatamente do Software. Pela extensão máxima permitida pela lei, a Benjamin A Padaria  reserva-se o direito de rescindir este contrato a qualquer momento e por qualquer motivo.</h4>
            <h4 class="info-title">7. PREVALÊNCIA</h4>
            <h4>As cláusulas das Seções deverão prevalecer sobre a rescisão ou o vencimento dos presentes Termos e Condições.</h4>
            <h4 class="info-title">8. ISENÇÃO</h4>
            <h4>O usuário concorda em não responsabilizar e/ou isentar a Benjamin A Padaria  e suas subsidiárias, afiliadas, diretores, agentes e funcionários no que tange a qualquer queixa, processo ou ação judicial decorrente do uso do Software, ou da sua violação a esses Termos e Condições, incluindo qualquer responsabilidade ou despesa decorrente de todas as reivindicações, perdas, danos, processos, julgamentos, custos de litígio e honorários advocatícios de qualquer natureza. Nesse caso, a Benjamin A Padaria  enviará a você uma notificação por escrito da mencionada queixa, processo ou ação.</h4>
            <h4 class="info-title">9. ISENÇÃO DE GARANTIAS</h4>
            <h4>VOCÊ COMPREENDE E CONCORDA EXPRESSAMENTE QUE:
            a) O USO DO SOFTWARE POR PARTE DO USUÁRIO É DE SUA INTEIRA RESPONSABILIDADE. O SOFTWARE É FORNECIDO "COMO ESTÁ" E SEM GARANTIA DE QUALQUER NATUREZA. PELA EXTENSÃO MÁXIMA PERMITIDA PELA LEI, A BENJAMIN A PADARIA  RENUNCIA EXPLICITAMENTE A TODAS AS GARANTIAS E CONDIÇÕES DE QUALQUER NATUREZA, SEJAM EXPRESSAS OU IMPLÍCITAS, INCLUINDO, SEM LIMITAÇÃO, AS CONDIÇÕES E GARANTIAS IMPLÍCITAS DE COMERCIALIDADE, ADEQUAÇÃO A QUALQUER FIM ESPECÍFICO E DE NÃO-VIOLAÇÃO.
            b) A BENJAMIN A PADARIA  NÃO DÁ NENHUMA GARANTIA (I) DE QUE O SOFTWARE ATENDERÁ ÀS EXIGÊNCIAS DO USUÁRIO; (II) O SOFTWARE ESTARÁ LIVRE DE ERROS OU FALHAS; (III) QUANTO À SEGURANÇA, CONFIABILIDADE, FUNCIONAMENTO EM TEMPO HÁBIL OU DESEMPENHO DO SOFTWARE; NEM DE QUE (IV) POSSÍVEIS ERROS DO SOFTWARE SERÃO CORRIGIDOS BREVEMENTE.
            c) TODO CONTEÚDO OU MATERIAL OBTIDO POR DOWNLOAD OU DE OUTRA FORMA ATRAVÉS DO USO DO SOFTWARE É OBTIDO A CRITÉRIO PRÓPRIO E EXCLUSIVO DO USUÁRIO, QUE SERÁ INTEIRAMENTE RESPONSÁVEL POR QUALQUER DANO QUE POSSA OCORRER NO SISTEMA DE COMPUTADOR OU OUTRO DISPOSITIVO OU PELA PERDA DE DADOS RESULTANTE DO DOWNLOAD DO REFERIDO CONTEÚDO OU MATERIAL.
            d) NENHUM AVISO OU INFORMAÇÃO, SEJA VERBAL OU POR ESCRITO, OBTIDO PELO USUÁRIO JUNTO A BENJAMIN A PADARIA  OU A TERCEIROS OU ATRAVÉS DO SOFTWARE, CARACTERIZA QUALQUER GARANTIA QUE NÃO ESTEJA EXPRESSAMENTE DESCRITA NESTES TERMOS E CONDIÇÕES.</h4>
            <h4 class="info-title">10. LIMITAÇÃO DE RESPONSABILIDADE</h4>
            <h4>O USUÁRIO COMPREENDE E ACEITA EXPRESSAMENTE QUE A BENJAMIN A PADARIA  NÃO ASSUME NENHUMA RESPONSABILIDADE POR NENHUM DANO DIRETO, INDIRETO, INCIDENTAL, ESPECIAL, EMERGENTE OU EXEMPLAR, INCLUINDO, SEM LIMITAÇÃO, OS DANOS POR LUCROS CESSANTES, PERDA DE REPUTAÇÃO, USO, DADOS OU OUTRAS PERDAS INTANGÍVEIS (MESMO QUE A BENJAMIN A PADARIA  TENHA SIDO NOTIFICADO DA POSSIBILIDADE DE TAIS DANOS) RESULTANTES DE: (I) MAL USO OU INCAPACIDADE DE USO DO SOFTWARE; (II) INCAPACIDADE DE USO DO SOFTWARE PARA ACESSAR CONTEÚDO OU DADOS; (III) CUSTO DE AQUISIÇÃO DE PRODUTOS OU SERVIÇOS SUBSTITUTOS; (IV) ACESSO NÃO AUTORIZADO A TRANSMISSÕES OU DADOS DO USUÁRIO OU ALTERAÇÃO DOS MESMOS; OU (V) QUALQUER OUTRO ASSUNTO RELACIONADO AO SOFTWARE. AS LIMITAÇÕES SUPRACITADAS SERÃO APLICADAS ENQUANTO PERMITIDO POR LEI, NÃO OBSTANTE A INEFICÁCIA DA FINALIDADE ESSENCIAL DE QUALQUER REMÉDIO JUDICIAL LIMITADO.</h4>
            <h4 class="info-title">11. EXCLUSÕES E LIMITAÇÕES</h4>
            <h4>NENHUMA CLÁUSULA DESTE CONTRATO VISA A EXCLUIR OU LIMITAR QUALQUER CONDIÇÃO, GARANTIA, DIREITO OU RESPONSABILIDADE QUE NÃO POSSA SER LEGALMENTE EXCLUÍDO OU LIMITADO. ALGUMAS JURISDIÇÕES NÃO PERMITEM A EXCLUSÃO DE DETERMINADAS GARANTIAS OU CONDIÇÕES NEM A LIMITAÇÃO OU EXCLUSÃO DE RESPONSABILIDADE POR PERDA OU DANO CAUSADO POR NEGLIGÊNCIA, VIOLAÇÃO DE CONTRATO</h4>
            <h4 class="info-title">12. AUSÊNCIA DE TERCEIROS BENEFICIÁRIOS</h4>
            <h4>O usuário concorda que, salvo quando previsto em contrário nestes Termos e Condições, nenhum terceiro será beneficiário destes Termos e Condições.</h4>
            <h4 class="info-title">13. SERVIÇOS DA BENJAMIN A PADARIA  E PRODUTOS E SERVIÇOS DE TERCEIROS</h4>
            <h4>Parte do Software da Benjamin A Padaria  foi projetada para ser usada juntamente com a pesquisa e outros serviços da Benjamin A Padaria . Por essa razão, a sua utilização de tal Software também é definida pelos Termos de Serviço da Benjamin A Padaria .</h4>
            <h4 class="info-title">14. DISPOSIÇÕES DIVERSAS</h4>
            <h4><ul> a) Contrato integral. Estes Termos e Condições constituem a íntegra do contrato entre o usuário e a Benjamin A Padaria  no que tange ao Software, e regem o uso deste, prevalecendo sobre quaisquer contratos anteriores ou atuais entre o usuário e a Benjamin A Padaria  no que tange ao Software.</ul>
            <ul>b) Escolha do foro competente. Estes Termos e Condições, bem como o relacionamento entre o usuário e a Benjamin A Padaria , serão regidos pela legislação do estado de São Paulo, no Brasil, independentemente das cláusulas sobre divergência de leis. O usuário e a Benjamin A Padaria  concordam em se subordinar à jurisdição pessoal e exclusiva dos tribunais situados na cidade de São Paulo, SP, Brasil.</ul>
            <ul>c) Renúncia de direitos e autonomia das cláusulas. O não exercício ou imposição de qualquer direito ou cláusula destes Termos e Condições por parte da Benjamin A Padaria  não constitui renúncia ao mencionado direito ou cláusula. Ainda que alguma cláusula destes Termos e Condições seja considerada inválida por qualquer tribunal de jurisdição competente, as partes envolvidas concordam que o tribunal deverá se empenhar para efetivar as intenções das partes envolvidas conforme estabelecidas na cláusula, sendo que as demais cláusulas destes Termos e Condições devem permanecer vigentes.</ul>
            <ul>d) Estatuto de limitações. O usuário concorda que, independentemente de qualquer estatuto ou lei em contrário, qualquer reivindicação ou causa de ação decorrente do uso do Software ou destes Termos e Condições, ou a eles relacionada, deverá ser legalmente apresentada dentro de um (1) ano a contar do surgimento dessa reivindicação ou causa de ação, ou ser vedada ad aeternum.</ul>
            <ul>e) Títulos. Os títulos das seções destes Termos e Condições foram elaborados meramente para fins de conveniência e não têm efeito legal ou contratual.</h4>
          </div>
        </div>
       <a href="registrar"><button type="button" class="btn btn-warning btn-round" style="margin-left: 45%;"> Voltar </button></a>
      </div>
    </div>
  </div>